// Generated by `npm run sync` from store.config.json — edit that file instead.
window.STORE_CONFIG = {
  "shopDomain": "1000errors.myshopify.com",
  "storefrontToken": "617d19f8f7af8d5dcdfd8233132e7629",
  "apiVersion": "2026-07"
};
